export const variables = [
  {
    slug: 'tas',
    description: 'Average air temperature at surface (1.5m)',
    nameLong: 'Average air temperature',
    name: 'Temperature',
    unitId: 1,
    startYear: 1884,
  },
  {
    slug: 'tmax',
    description: 'Maximum air temperature at surface (1.5m)',
    nameLong: 'Maximum air temperature',
    name: 'Max. temperature',
    unitId: 1,
    startYear: 1884,
  },
  {
    slug: 'tmin',
    description: 'Minimum air temperature at surface (1.5m)',
    nameLong: 'Minimum air temperature',
    name: 'Min. temperature',
    unitId: 1,
    startYear: 1884,
  },
  {
    slug: 'rainfall',
    description: 'Total rainfall (mm)',
    nameLong: 'Total rainfall',
    name: 'Rainfall',
    unitId: 2,
    startYear: 1961,
  },
  {
    slug: 'sun',
    description: 'Sunshine hours (h)',
    nameLong: 'Sunshine hours',
    name: 'Sunshine',
    unitId: 3,
    startYear: 1961,
  },
  {
    slug: 'sfcWind',
    description: 'Wind speed at 10m',
    nameLong: 'Wind speed at 10m',
    name: 'Wind',
    unitId: 6,
    startYear: 1961,
  },
  {
    slug: 'hurs',
    description: 'Relative humidity at 1.5m (%)',
    nameLong: 'Relative humidity',
    name: 'Humidity',
    unitId: 5,
    startYear: 1961,
  },
  {
    slug: 'groundfrost',
    description: 'Days of ground frost (days)',
    nameLong: 'Days of ground frost',
    name: 'Frost',
    unitId: 4,
    startYear: 1961,
  },
  {
    slug: 'snowLying',
    description: 'Days of snow lying (days)',
    nameLong: 'Days of snow lying',
    name: 'Snow',
    unitId: 4,
    startYear: 1961,
  },
]
